name: heart_zone_training
description: An app for heart rate zone training.

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^0.1.6
  shared_preferences: ^0.4.2
  audioplayers: ^0.7.5
  flutter_ble_lib: "^1.0.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/
